import Banner from '../components/Banner';
import BlogBanner from '../components/BlogBanners';
import Footer from '../components/Footer';
import Header from '../components/Header';
import '../globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-hero bg-local bg-cover bg-no-repeat bg-bottom w-full h-96 md:h-72 md:mb-8">
          <div className="backdrop-brightness-75 h-full">
            <Header />
            <BlogBanner />
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
